// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMonitoringSourceData, CreateMonitoringSourceErrors, CreateMonitoringSourceResponses, CreateMonitorTriggerData, CreateMonitorTriggerErrors, CreateMonitorTriggerResponses, DeleteMonitoringSourceData, DeleteMonitoringSourceErrors, DeleteMonitoringSourceResponses, DeleteMonitorTriggerData, DeleteMonitorTriggerErrors, DeleteMonitorTriggerResponses, GetMonitoringSourceData, GetMonitoringSourceErrors, GetMonitoringSourceResponses, GetMonitoringSourcesByUserData, GetMonitoringSourcesByUserErrors, GetMonitoringSourcesByUserResponses, GetMonitoringSourceViewsData, GetMonitoringSourceViewsErrors, GetMonitoringSourceViewsResponses, GetMonitorTriggerData, GetMonitorTriggerErrors, GetMonitorTriggerResponses, HealthCheckData, HealthCheckResponses, UpdateMonitoringSourceData, UpdateMonitoringSourceErrors, UpdateMonitoringSourceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health/monitoring',
    ...options
});

/**
 * Get Monitoring Sources By User
 */
export const getMonitoringSourcesByUser = <ThrowOnError extends boolean = false>(options?: Options<GetMonitoringSourcesByUserData, ThrowOnError>) => (options?.client ?? client).get<GetMonitoringSourcesByUserResponses, GetMonitoringSourcesByUserErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitoring-sources',
    ...options
});

/**
 * Create Monitoring Source
 */
export const createMonitoringSource = <ThrowOnError extends boolean = false>(options: Options<CreateMonitoringSourceData, ThrowOnError>) => (options.client ?? client).post<CreateMonitoringSourceResponses, CreateMonitoringSourceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitoring-sources',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Monitoring Source Views
 */
export const getMonitoringSourceViews = <ThrowOnError extends boolean = false>(options: Options<GetMonitoringSourceViewsData, ThrowOnError>) => (options.client ?? client).get<GetMonitoringSourceViewsResponses, GetMonitoringSourceViewsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitoring-sources/{id}/views',
    ...options
});

/**
 * Delete Monitoring Source
 */
export const deleteMonitoringSource = <ThrowOnError extends boolean = false>(options: Options<DeleteMonitoringSourceData, ThrowOnError>) => (options.client ?? client).delete<DeleteMonitoringSourceResponses, DeleteMonitoringSourceErrors, ThrowOnError>({ url: '/monitoring-sources/{id}', ...options });

/**
 * Get Monitoring Source
 */
export const getMonitoringSource = <ThrowOnError extends boolean = false>(options: Options<GetMonitoringSourceData, ThrowOnError>) => (options.client ?? client).get<GetMonitoringSourceResponses, GetMonitoringSourceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitoring-sources/{id}',
    ...options
});

/**
 * Update Monitoring Source
 */
export const updateMonitoringSource = <ThrowOnError extends boolean = false>(options: Options<UpdateMonitoringSourceData, ThrowOnError>) => (options.client ?? client).put<UpdateMonitoringSourceResponses, UpdateMonitoringSourceErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitoring-sources/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Monitor Trigger
 */
export const deleteMonitorTrigger = <ThrowOnError extends boolean = false>(options?: Options<DeleteMonitorTriggerData, ThrowOnError>) => (options?.client ?? client).delete<DeleteMonitorTriggerResponses, DeleteMonitorTriggerErrors, ThrowOnError>({ url: '/monitor-triggers', ...options });

/**
 * Get Monitor Trigger
 */
export const getMonitorTrigger = <ThrowOnError extends boolean = false>(options?: Options<GetMonitorTriggerData, ThrowOnError>) => (options?.client ?? client).get<GetMonitorTriggerResponses, GetMonitorTriggerErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitor-triggers',
    ...options
});

/**
 * Create Monitor Trigger
 */
export const createMonitorTrigger = <ThrowOnError extends boolean = false>(options: Options<CreateMonitorTriggerData, ThrowOnError>) => (options.client ?? client).post<CreateMonitorTriggerResponses, CreateMonitorTriggerErrors, ThrowOnError>({
    responseType: 'json',
    url: '/monitor-triggers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
