// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MonitorTrigger
 *
 * Model for monitor trigger.
 */
export type MonitorTrigger = {
    /**
     * Language
     *
     * The language that workflow generates data in by the trigger
     */
    language: string;
    /**
     * User Id
     *
     * ID of user who created the trigger
     */
    user_id: string;
};

/**
 * MonitorTriggerMainData
 *
 * Model for monitor trigger.
 */
export type MonitorTriggerMainData = {
    /**
     * Language
     *
     * The language that workflow generates data in by the trigger
     */
    language: string;
};

/**
 * MonitoringSource
 */
export type MonitoringSource = {
    /**
     * Name
     *
     * Name of the monitoring source
     */
    name?: string | null;
    /**
     * Description
     *
     * Describe what kind of information the source focuses on
     */
    description?: string | null;
    /**
     * Type of the monitoring source such as 'website', 'twitter', 'telegram'
     */
    type?: SourceType | null;
    /**
     * Url
     *
     * URL of the monitoring source
     */
    url?: string | null;
    /**
     * Reliability
     *
     * Reliability score of the monitoring source, ranging from 0 to 100
     */
    reliability?: number | null;
    /**
     * Last Reviewed
     *
     * The last time the source was reviewed, in epoch time
     */
    last_reviewed?: number | null;
    /**
     * Attributes
     *
     * Platform-specific identifiers or handles required to monitor the source via API calls. Examples include a Twitter user id or a Telegram channel ID.
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
    /**
     * Owner
     *
     * Identify the user the monitoring source belongs to
     */
    owner: string;
};

/**
 * MonitoringSourceMainData
 */
export type MonitoringSourceMainData = {
    /**
     * Name
     *
     * Name of the monitoring source
     */
    name?: string | null;
    /**
     * Description
     *
     * Describe what kind of information the source focuses on
     */
    description?: string | null;
    /**
     * Type of the monitoring source such as 'website', 'twitter', 'telegram'
     */
    type?: SourceType | null;
    /**
     * Url
     *
     * URL of the monitoring source
     */
    url?: string | null;
    /**
     * Reliability
     *
     * Reliability score of the monitoring source, ranging from 0 to 100
     */
    reliability?: number | null;
    /**
     * Last Reviewed
     *
     * The last time the source was reviewed, in epoch time
     */
    last_reviewed?: number | null;
    /**
     * Attributes
     *
     * Platform-specific identifiers or handles required to monitor the source via API calls. Examples include a Twitter user id or a Telegram channel ID.
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
};

/**
 * OsintView
 */
export type OsintView = {
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
    /**
     * Name
     *
     * Name of the view
     */
    name?: string | null;
    /**
     * Description
     *
     * Description of the view
     */
    description?: string | null;
    /**
     * Analysis
     *
     * Json based analysis report doc
     */
    analysis?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * SourceType
 */
export type SourceType = 'website' | 'twitter' | 'telegram';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetMonitoringSourcesByUserData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/monitoring-sources';
};

export type GetMonitoringSourcesByUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitoringSourcesByUserError = GetMonitoringSourcesByUserErrors[keyof GetMonitoringSourcesByUserErrors];

export type GetMonitoringSourcesByUserResponses = {
    /**
     * Response Get Monitoring Sources By User
     *
     * Successful Response
     */
    200: Array<MonitoringSource>;
};

export type GetMonitoringSourcesByUserResponse = GetMonitoringSourcesByUserResponses[keyof GetMonitoringSourcesByUserResponses];

export type CreateMonitoringSourceData = {
    body: MonitoringSourceMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/monitoring-sources';
};

export type CreateMonitoringSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMonitoringSourceError = CreateMonitoringSourceErrors[keyof CreateMonitoringSourceErrors];

export type CreateMonitoringSourceResponses = {
    /**
     * Successful Response
     */
    200: MonitoringSource;
};

export type CreateMonitoringSourceResponse = CreateMonitoringSourceResponses[keyof CreateMonitoringSourceResponses];

export type GetMonitoringSourceViewsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    query?: never;
    url: '/monitoring-sources/{id}/views';
};

export type GetMonitoringSourceViewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitoringSourceViewsError = GetMonitoringSourceViewsErrors[keyof GetMonitoringSourceViewsErrors];

export type GetMonitoringSourceViewsResponses = {
    /**
     * Response Get Monitoring Source Views
     *
     * Successful Response
     */
    200: Array<OsintView>;
};

export type GetMonitoringSourceViewsResponse = GetMonitoringSourceViewsResponses[keyof GetMonitoringSourceViewsResponses];

export type DeleteMonitoringSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    query?: never;
    url: '/monitoring-sources/{id}';
};

export type DeleteMonitoringSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMonitoringSourceError = DeleteMonitoringSourceErrors[keyof DeleteMonitoringSourceErrors];

export type DeleteMonitoringSourceResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMonitoringSourceResponse = DeleteMonitoringSourceResponses[keyof DeleteMonitoringSourceResponses];

export type GetMonitoringSourceData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    query?: never;
    url: '/monitoring-sources/{id}';
};

export type GetMonitoringSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitoringSourceError = GetMonitoringSourceErrors[keyof GetMonitoringSourceErrors];

export type GetMonitoringSourceResponses = {
    /**
     * Successful Response
     */
    200: MonitoringSource;
};

export type GetMonitoringSourceResponse = GetMonitoringSourceResponses[keyof GetMonitoringSourceResponses];

export type UpdateMonitoringSourceData = {
    body: MonitoringSourceMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
    };
    query?: never;
    url: '/monitoring-sources/{id}';
};

export type UpdateMonitoringSourceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMonitoringSourceError = UpdateMonitoringSourceErrors[keyof UpdateMonitoringSourceErrors];

export type UpdateMonitoringSourceResponses = {
    /**
     * Successful Response
     */
    200: MonitoringSource;
};

export type UpdateMonitoringSourceResponse = UpdateMonitoringSourceResponses[keyof UpdateMonitoringSourceResponses];

export type DeleteMonitorTriggerData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/monitor-triggers';
};

export type DeleteMonitorTriggerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMonitorTriggerError = DeleteMonitorTriggerErrors[keyof DeleteMonitorTriggerErrors];

export type DeleteMonitorTriggerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMonitorTriggerResponse = DeleteMonitorTriggerResponses[keyof DeleteMonitorTriggerResponses];

export type GetMonitorTriggerData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/monitor-triggers';
};

export type GetMonitorTriggerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonitorTriggerError = GetMonitorTriggerErrors[keyof GetMonitorTriggerErrors];

export type GetMonitorTriggerResponses = {
    /**
     * Successful Response
     */
    200: MonitorTrigger;
};

export type GetMonitorTriggerResponse = GetMonitorTriggerResponses[keyof GetMonitorTriggerResponses];

export type CreateMonitorTriggerData = {
    body: MonitorTriggerMainData;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/monitor-triggers';
};

export type CreateMonitorTriggerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMonitorTriggerError = CreateMonitorTriggerErrors[keyof CreateMonitorTriggerErrors];

export type CreateMonitorTriggerResponses = {
    /**
     * Successful Response
     */
    200: MonitorTrigger;
};

export type CreateMonitorTriggerResponse = CreateMonitorTriggerResponses[keyof CreateMonitorTriggerResponses];
